//
//  .SwitfLint.yml
//  Swift-SolidPrinicple
//
//  Created by ReetDhillon on 2024-02-07.
//

import Foundation

opt_in_rules
    - indentation_width
    - explicit_self
    - operator_usage_whitespace
